INSERT OR IGNORE INTO course_prefixes(prefix, subject)
VALUES ('ACC','Accounting'),
       ('AH','Allied Heath'),
       ('AR','Art'),
       ('BIO','Biological Science'),
       ('BMA','Business Math'),
       ('BUS','Business'),
       ('CA', 'College of Hummanities and Social Sciences'),
       ('CH','Chemistry'),
       ('CJ','Criminal Justice'),
       ('CO','Communication'),
       ('CS','Computer Science'),
       ('CT','Computer Engineering Technology'),
       ('ECN','Economics'),
       ('EL','Elective'),
       ('EMT','Engineering Management Technology'),
       ('EN','English'),
       ('ENT','Entrepreneurship'),
       ('ET','Electronics Engineering'),
       ('ETH','Ethnics'),
       ('FIN','Finance'),
       ('GP','Government and Politics'),
       ('GS','General Science'),
       ('GU','Grantham University'),
       ('HP','Health Professionals'),
       ('HRM','Human Resource Management/HPI'),
       ('HS','History'),
       ('HSN','Nursing and Health Professionals'),
       ('HU','Humanities'),
       ('ID','Interdisciplinary'),
       ('IS','Information Systems'),
       ('INT','International/Global'),
       ('IT','Information Technology'),
       ('LAW','Law'),
       ('LD','Leadership'),
       ('LOG','Logistics'),
       ('MA','Mathematics'),
       ('MGT','Management/HRM/HPI'),
       ('MIL','Military'),
       ('MKG','Marketing'),
       ('NUR','Nursing'),
       ('PA','Public Adminstration'),
       ('PH','Physics'),
       ('PL','Philosophy'),
       ('PLS','Paralegal Studies'),
       ('PRJ','Project Management'),
       ('PS','Psychology'),
       ('RCH','Quantitative/Qualitative/Research'),
       ('SO','Sociology'),
       ('SS','Social Science');
